# Generated by Django 2.1.5 on 2019-01-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='boards',
            new_name='board',
        ),
    ]
